### ISSUE TITLE
alma 8.5

### ISSUE THREAD

**Issue by hadasvol** [andygeorgi/az_custom_hpc_images#3]
Hi, thanks for the build scripts. 
May you offer an update for setting up an hpc variant for the latest alma 8.5 base image?

**Comment by andygeorgi** [comment]
> Hi, thanks for the build scripts. May you offer an update for setting up an hpc variant for the latest alma 8.5 base image?

I'm starting to work on that. I'll get back to you as soon as I'm done.

**Comment by andygeorgi** [comment]
Support for Alma Linux 8.5 gen1 added: a59b9a4c66736ae17dcbb35d18febd06d0e7f3fd
Support for Alma Linux 8.5 gen2 added: 18bc82ed3998adbef5375d75dca2d739b54bffcf
